### ISSUE TITLE
appsody build fails: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by tnixa** [appsody/appsody#675]
**Describe the bug**
Doing an `appsody stack validate` on the nodejs-express stack and I noticed the `build` step is failing. Log is here: 
[build_fail.log](https://github.com/appsody/appsody/files/3870815/build_fail.log)

The failure can also be recreated with `appsody build` using the latest appsody CLI code

**To Reproduce**
1. clone appsody repo
2. `cd appsody`
3. `go build`
4. `mkdir nodejs-express1
5. `cd nodejs-express`
6. run `appsody init nodejs-express` wtih the built appsody binary 
example: `/Users/tnixa/go/src/github.com/appsody/appsody/appsody init`
7. run `appsody build` wtih the built appsody binary 
example: `/Users/tnixa/go/src/github.com/appsody/appsody/appsody build`

**Expected behavior**
`appsody build` should not fail

**Actual behaviour**
```
Running command: docker rm nodejs-express-extract -f
Running git command: git version
Running git command: git status -sb
git command failed:
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/appsody/appsody/cmd.updateDeploymentConfig(0xc000430100, 0x3a, 0xc000294840)
	/Users/tnixa/go/src/github.com/appsody/appsody/cmd/build.go:512 +0x2a6
github.com/appsody/appsody/cmd.generateDeploymentConfig(0xc000430100, 0x4, 0x0)
	/Users/tnixa/go/src/github.com/appsody/appsody/cmd/build.go:477 +0x178b
github.com/appsody/appsody/cmd.build(0xc000430100, 0x0, 0x0)
	/Users/tnixa/go/src/github.com/appsody/appsody/cmd/build.go:204 +0x9dd
github.com/appsody/appsody/cmd.newBuildCmd.func1(0xc00017e500, 0x23106a8, 0x0, 0x0, 0x0, 0x0)
	/Users/tnixa/go/src/github.com/appsody/appsody/cmd/build.go:95 +0xcb
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).execute(0xc00017e500, 0x23106a8, 0x0, 0x0, 0xc00017e500, 0x23106a8)
	/Users/tnixa/go/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00038f180, 0x5, 0x0, 0x1bc2fa0)
	/Users/tnixa/go/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/tnixa/go/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:800
github.com/appsody/appsody/cmd.ExecuteE(0x1a5785f, 0x7, 0x1a56c6e, 0x6, 0xc00003c034, 0x2a, 0x1bc2fa0, 0xc000010010, 0x1bc2fa0, 0xc000010018, ...)
	/Users/tnixa/go/src/github.com/appsody/appsody/cmd/root.go:212 +0x327
github.com/appsody/appsody/cmd.Execute(0x1a5785f, 0x7, 0x1a56c6e, 0x6)
	/Users/tnixa/go/src/github.com/appsody/appsody/cmd/root.go:198 +0x1ab
main.main()
	/Users/tnixa/go/src/github.com/appsody/appsody/main.go:27 +0x51
supra:nodejs-express tnixa$ echo $?
2
```

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] mac

**If applicable please specify:**
 - CLI version: lastest master branch code
 - Stack you are using: nodejs-express

**Comment by EnriqueL8** [comment]
`appsodyApplication.Labels` could be nil which means that a line `512` we are trying to insert into a nil map
