### ISSUE TITLE
panic when .appsody-config.yaml contains a license

### ISSUE THREAD

**Issue by kylegc** [appsody/appsody#768]
**Describe the bug**
When the project `.appsody-config.yaml` file contains a valid license, the `appsody build` command results in this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x18960b7]

goroutine 1 [running]:
github.com/appsody/appsody/cmd.checkValidLicense(0xc0003c2078, 0x3, 0x1a68b01, 0x0)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/utils.go:2054 +0x37
github.com/appsody/appsody/cmd.getConfigLabels(0xc00014c180, 0x2a, 0xc0003c2050, 0x9, 0x0, 0x0, 0xc0003c2090, 0x5, 0xc0003c20e0, 0xf, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/utils.go:659 +0x6cc
github.com/appsody/appsody/cmd.getLabels(0xc00029e990, 0xc0002aac80, 0x0, 0x2a)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/build.go:228 +0x110
github.com/appsody/appsody/cmd.build(0xc00040fa00, 0x0, 0x0)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/build.go:172 +0x4e5
github.com/appsody/appsody/cmd.newBuildCmd.func1(0xc0002eea00, 0x230d468, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/build.go:95 +0xcb
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).execute(0xc0002eea00, 0x230d468, 0x0, 0x0, 0xc0002eea00, 0x230d468)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000431180, 0x5, 0x0, 0x1bc0ae0)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/appsody/appsody/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/appsody/appsody/vendor/github.com/spf13/cobra/command.go:800
github.com/appsody/appsody/cmd.ExecuteE(0x1bab900, 0x5, 0x1bab8f8, 0x5, 0xc00003c004, 0x21, 0x1bc0ae0, 0xc0000be000, 0x1bc0ae0, 0xc0000c2000, ...)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:217 +0x327
github.com/appsody/appsody/cmd.Execute(0x1bab900, 0x5, 0x1bab8f8, 0x5)
	/home/travis/gopath/src/github.com/appsody/appsody/cmd/root.go:203 +0x1ab
main.main()
	/home/travis/gopath/src/github.com/appsody/appsody/main.go:27 +0x51
```

**To Reproduce**
1. init an appsody project
2. add `license: MIT` to the `.appsody-config.yaml` flie
3. run `appsody build`

**Expected behavior**
build should work

**Actual behaviour**
build fails with go panic

**Environment Details (please complete the following information):**
 - OS: macOS
 - Version: appsody 0.5.2

**Comment by skoh7645** [comment]
@kylegc I couldn't replicate this error, what stack were you using? I tried it on `nodejs-express` and it worked with a valid license, and failed with an invalid license as expected. I also noticed the built image is tagged with `dev.local/<stack`. Is that what we wanted?

**Comment by kylegc** [comment]
Hmm that's odd. It seems to fail on all stacks for me. I tried nodejs, nodejs-express, spring, and microprofile. Here's an example of the `.appsody-config.yaml`
```
project-name: nodejs
license: MIT
stack: appsody/nodejs:0.2
```
